[versions]
graalJs = "24.1.2"
networknt = "1.5.5"

[libraries]
graalJs = { module = "org.graalvm.js:js", version.ref = "graalJs" }
networknt = { module = "com.networknt:json-schema-validator", version.ref = "networknt" }
