[versions]
validator = "0.3.1"

[libraries]
validator = { module = "io.github.optimumcode:json-schema-validator", version.ref = "validator" }

[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.1.10" }
